import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Frontpage</Link>
        </li>
        <li>
          <Link to="/bannerone">BannerOne</Link>
        </li>
        <li>
          <Link to="/banner">Banner</Link>
        </li>
        <li>
          <Link to="/frame152">Frame152</Link>
        </li>
        <li>
          <Link to="/homepage">Homepage</Link>
        </li>
        <li>
          <Link to="/detaliedlistingpage">DetaliedListingPage</Link>
        </li>
        <li>
          <Link to="/agencylistpage">AgencyListPAge</Link>
        </li>
        <li>
          <Link to="/premiumescape">PremiumEscape</Link>
        </li>
        <li>
          <Link to="/addaprofile">AddaProfile</Link>
        </li>
        <li>
          <Link to="/blog">Blog</Link>
        </li>
        <li>
          <Link to="/registration">Registration</Link>
        </li>
        <li>
          <Link to="/myprofilesidebaar">Myprofilesidebaar</Link>
        </li>
        <li>
          <Link to="/contactus">ContactUs</Link>
        </li>
        <li>
          <Link to="/searchpage">Searchpage</Link>
        </li>
        <li>
          <Link to="/membershipplan">Membershipplan</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
